/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaintingResponse } from '../../models/painting-response';

export interface GetPaintingById$Params {
  id: number;
}

export function getPaintingById(http: HttpClient, rootUrl: string, params: GetPaintingById$Params, context?: HttpContext): Observable<StrictHttpResponse<PaintingResponse>> {
  const rb = new RequestBuilder(rootUrl, getPaintingById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaintingResponse>;
    })
  );
}

getPaintingById.PATH = '/painting/{id}';
