/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BorrowedPaintingResponse {
  artist?: string;
  doi?: string;
  id?: number;
  rating?: number;
  returnApproved?: boolean;
  returned?: boolean;
  title?: string;
}
