/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BorrowedPaintingResponse } from '../models/borrowed-painting-response';
export interface PageResponseBorrowedPaintingResponse {
  content?: Array<BorrowedPaintingResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
