/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PaintingResponse {
  archived?: boolean;
  artist?: string;
  doi?: string;
  id?: number;
  image?: string;
  info?: string;
  owner?: string;
  rating?: number;
  shareable?: boolean;
  title?: string;
}
