/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PaintingRequest {
  artist: string;
  doi: string;
  id?: number;
  info: string;
  shareable?: boolean;
  title: string;
}
